### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by ritvij14** [cryptoplease/cryptoplease-dart#188]
I am trying to make a basic app to create a new token and mint it.
https://github.com/ritvij14/solana_token_swap_flutter

So after initialising these addresses:

```dart
String randomMnemonic = bip39.generateMnemonic();
wallet = await Ed25519HDKeyPair.fromMnemonic(randomMnemonic);
mint = await Ed25519HDKeyPair.random();
freezeAuthority = await Ed25519HDKeyPair.random();
mintAuthority = await Ed25519HDKeyPair.random();
```

I have a basic button which activates a `initializeMint` instruction:

```dart
void _createToken() async {
    // initialize mint
    final rent = await rpcClient
        .getMinimumBalanceForRentExemption(TokenProgram.neededMintAccountSpace);
    await sendMessage(
      TokenProgram.initializeMint(
        mint: mint.address,
        mintAuthority: mintAuthority.address,
        freezeAuthority: freezeAuthority.address,
        rent: rent,
        space: TokenProgram.neededMintAccountSpace,
        decimals: 5,
      ),
      [mintAuthority, mint],
    );

    // display result
    print("token minting done");
  }
```

Code for `sendMessage`:

```dart
Future<void> sendMessage(
    Message message,
    List<Ed25519HDKeyPair> signers,
  ) =>
      _sendMessage(
        rpcClient: rpcClient,
        subscriptionClient: subscriptionClient,
        message: message,
        signers: signers,
      );

  Future<void> _sendMessage({
    required RpcClient rpcClient,
    required SubscriptionClient subscriptionClient,
    required Message message,
    required List<Ed25519HDKeyPair> signers,
  }) async {
    final signature = await rpcClient.signAndSendTransaction(message, signers);
    await subscriptionClient.waitForSignatureStatus(
      signature,
      status: ConfirmationStatus.finalized,
    );
  }
```

And this is the error log I get on clicking the button that runs the function:

```bash
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1282:9)
#1      _rootRun (dart:async/zone.dart:1418:47)
#2      _CustomZone.run (dart:async/zone.dart:1328:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
#6      _DelayedDone.perform (dart:async/stream_impl.dart:610:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#9      _rootRun (dart:async/zone.dart:1418:47)
#10     _CustomZone.run (dart:async/zone.dart:1328:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#13     _rootRun (dart:async/zone.dart:142<…>
```

**Comment by ritvij14** [comment]
Sometimes I am also not getting this error.

And once mint initialization is done, and I go for `mintTo`, I get the below error, even though I am not sending any Program token from my end:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: jsonrpc-2.0 error (-32002): Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction
        {accounts: null, err: {InstructionError: [0, InvalidAccountData]}, logs: [Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1], Program log: Instruction: MintTo, Program log: Error: InvalidAccountData, Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1411 of 200000 compute units, Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction], unitsConsumed: 0}
#0      new _JsonRpcResponse._fromObject (package:solana/src/rpc/json_rpc_client.dart:135:7)
#1      new _JsonRpcResponse._parse (package:solana/src/rpc/json_rpc_client.dart:157:31)
#2      JsonRpcClient._postRequest (package:solana/src/rpc/json_rpc_client.dart:79:31)
<asynchronous suspension>
#3      JsonRpcClient.request (package:solana/src/rpc/json_rpc_client.dart:54:22)
<asynchronous suspension>
#4      <…>
```

**Comment by ookami-kb** [comment]
I see that you're using low-level API. Can you try it with `SolanaClient.initializeMint()` method?

**Comment by ritvij14** [comment]
@ookami-kb alright trying with that now.

**Comment by ritvij14** [comment]
@ookami-kb 

I used this:
```dart
await client.initializeMint(
      owner: mint,
      decimals: 5,
      freezeAuthority: freezeAuthority.address,
      mintAuthority: mintAuthority.address,
    );
```

And I got this error:
```bash
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FormatException: your message requires 3 signatures but you provided 2
#0      signTransaction (package:solana/src/helpers.dart:106:5)
#1      RpcClientExt.signAndSendTransaction (package:solana/src/rpc/extension.dart:10:28)
<asynchronous suspension>
#2      SolanaClient.initializeMint (package:solana/src/solana_client.dart:142:23)
<asynchronous suspension>
#3      _MyHomePageState._createToken (package:solana_token_swap_flutter/main.dart:104:5)
<asynchronous suspension>
```

What is the third signer?

**Comment by ritvij14** [comment]
@ookami-kb update, I went over the code for tests of SolanaClient, and wrote code in that way and I was able to run the entire set of functions to create a new token.

**Comment by antoineherzog** [comment]
Closing the ticket then
